name = "stresstest-ai"
main = "src/index.ts"
compatibility_date = "2025-07-11"


[vars]
GUMROAD_PRODUCT_ID = ""
FREE_DAILY_LIMIT = "3"

[[kv_namespaces]]
binding = "KV"
id = ""
preview_id = ""
node_compat = true

[[kv_namespaces]]
binding = "INBOX_KV"
id = "6ede4b43b18f47248e97ce13f56a4c26"
preview_id = "6ede4b43b18f47248e97ce13f56a4c26"

[[kv_namespaces]]
binding = "TASK_KV"
id = "83dd0faf543d4fafabd9f3e6627a7cf7"
preview_id = "83dd0faf543d4fafabd9f3e6627a7cf7"
